### ISSUE TITLE
Incompatible with stemcell range 3541

### ISSUE THREAD

**Issue by camelpunch** [cloudfoundry-community/logsearch-boshrelease#115]
The 3541 range includes a [change to the default umask to be 077](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/c968b78c4b8dcb8a3b1fac6d40a8ee518fea6c57). This means that, at least on our old crufty 203.0.0 logsearch, the config file can't be read:

```
Exception in thread "main" SettingsException[Failed to open stream for url [/var/vcap/packages/elasticsearch/config/elasticsearch.yml]]; nested: AccessDeniedException[/var/vcap/packages/elasticsearch/config/elasticsearch.yml];
Likely root cause: java.nio.file.AccessDeniedException: /var/vcap/packages/elasticsearch/config/elasticsearch.yml
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at org.elasticsearch.common.settings.Settings$Builder.loadFromPath(Settings.java:1061)
        at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:88)
        at org.elasticsearch.common.cli.CliTool.<init>(CliTool.java:107)
        at org.elasticsearch.common.cli.CliTool.<init>(CliTool.java:100)
        at org.elasticsearch.bootstrap.BootstrapCLIParser.<init>(BootstrapCLIParser.java:48)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:241)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
```

Haven't reproduced on latest release yet. Thought it'd be worth recording here, though.

**Comment by FlorianNachtigall** [comment]
We also experience the same issue on 203.0.0 for the new version of the stemcell [3541.4](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/releases/tag/stable-3541.4) with the rolled back umask changes.

**Comment by Infra-Red** [comment]
@camelpunch @FlorianNachtigall Since release v207.0.0 elasticsearch job is using `path.conf` property to read config file from `/var/vcap/jobs/elasticsearch/config` folder. Latest v209.0.0 release works as expected with 3541.latest stemcell version.

https://github.com/cloudfoundry-community/logsearch-boshrelease/commit/4508d9acab0dfe3a43af57cfa4fe3d885f70e47b#diff-df08e431dda0ea301e3e3081a57ec33dR58
