### ISSUE TITLE
Intermittent errors with v209 (and logsearch-for-cloudfoundry v207)

### ISSUE THREAD

**Issue by will-gant** [cloudfoundry-community/logsearch-boshrelease#120]
Ever since we upgraded to v209 logsearch and v207 logsearch-for-cloudfoundry we have experienced intermittent failures during the `bosh deploy` (it succeeds about two-thirds of the time). We are seeing this on multiple CF foundations.

The error is:

```
Task 2325 | 15:51:56 | Preparing deployment: Preparing deployment (00:00:03)
Task 2325 | 15:52:02 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 2325 | 15:52:03 | Updating instance ingestor: ingestor/4ca16052-62d0-425b-901b-40a2984df4fd (0) (canary) (00:03:39)
                     L Error: 'ingestor/4ca16052-62d0-425b-901b-40a2984df4fd (0)' is not running after update. Review logs for failed jobs: ingestor_cloudfoundry-firehose
Task 2325 | 15:55:42 | Error: 'ingestor/4ca16052-62d0-425b-901b-40a2984df4fd (0)' is not running after update. Review logs for failed jobs: ingestor_cloudfoundry-firehose
```

The logs from the `ingestor_cloudfoundry-firehose` job on the failed vm include the following:

from `ingestor_cloudfoundry-firehose.stderr.log`
```
[2018-05-03 16:36:44.325211233 +0000 UTC] Exception occurred! Message: Error open cache:  Details: Error requesting orgs: cfclient: error (1000): CF-InvalidAuthToken
[2018-05-03 16:41:59.371898116 +0000 UTC] Exception occurred! Message: Error while listing organization: %v Details: Error requesting orgs: cfclient: error (1000): CF-InvalidAuthToken
[2018-05-03 16:41:59.372065147 +0000 UTC] Exception occurred! Message: Error open cache:  Details: Error requesting orgs: cfclient: error (1000): CF-InvalidAuthToken
[2018-05-03 16:47:14.371006361 +0000 UTC] Exception occurred! Message: Error while listing organization: %v Details: Error requesting orgs: cfclient: error (1000): CF-InvalidAuthToken
[2018-05-03 16:47:14.37106533 +0000 UTC] Exception occurred! Message: Error open cache:  Details: Error requesting orgs: cfclient: error (1000): CF-InvalidAuthToken
```

from `ingestor_cloudfoundry-firehose.stdout.log`
```
[2018-05-03 16:41:59.219685402 +0000 UTC] Using wss://doppler.<system-domain>:4443 as doppler endpoint
[2018-05-03 16:47:14.16962369 +0000 UTC] Starting firehose-to-syslog 0.0.0
wss://doppler.<system-domain>:4443
[2018-05-03 16:47:14.227704593 +0000 UTC] Using wss://doppler.<system-domain>:4443 as doppler endpoint
```

It seems strange that this doesn't fail most of the time but when it does fail the errors are the same. We don't change anything between successes and failures.

**Comment by will-gant** [comment]
Further to the above, we fished the following logs out of one of our Cloud Controller VMs. The timestamp matches exactly with an error in `ingestor_cloudfoundry-firehose.stderr.log` like the one pasted above.

For the avoidance of doubt, we've checked the manifest that our logsearch was deployed with, and it has the correct secrets, etc (indeed, these are apparently accepted part of the time, on those occasions where the deploy succeeds).

Another interesting thing we've discovered is that the deployments fail less often (but do still fail sometimes) when we scale down to a single instance of `ingestor` from two. Bizarre.

```
{
  "timestamp": 1525776562.146358,
  "message": "Request failed: 401: {\"description\"=>\"Invalid Auth Token\",
     \"error_code\"=>\"CF-InvalidAuthToken\",
     \"code\"=>1000,
     \"test_mode_info\"=>{\"description\"=>\"Invalid Auth Token\",
     \"error_code\"=>\"CF-InvalidAuthToken\",
     \"backtrace\"=>[\"/var/vcap/data/packages/cloud_controller_ng/81787820a0caca12db89049698f3f2f35031aa65/cloud_controller_ng/app/controllers/base/base_controller.rb:135:in `check_authentication'\",
     \"/var/vcap/data/packages/cloud_controller_ng/81787820a0caca12db89049698f3f2f35031aa65/cloud_controller_ng/app/controllers/base/base_controller.rb:77:in `dispatch'\",
     \"/var/vcap/data/packages/cloud_controller_ng/81787820a0caca12db89049698f3f2f35031aa65/cloud_controller_ng/lib/cloud_controller/rest_controller/routes.rb:16:in `block in define_route'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1610:in `call'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1610:in `block in compile!'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/nulllogger.rb:9:in `call'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/cef_logs.rb:18:in `call'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/request_logs.rb:22:in `call'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/security_context_setter.rb:19:in `call'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/vcap_request_id.rb:15:in `call'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/cors.rb:49:in `call_app'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/cors.rb:14:in `call'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/request_metrics.rb:12:in `call'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/builder.rb:153:in `call'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:86:in `block in pre_process'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `catch'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `pre_process'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:50:in `block in process'\",
     \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in `block in spawn_threadpool'\"]}}",
  "log_level": "info",
  "source": "cc.api",
  "data": {
    "request_guid": "a6fa19d9-3d1c-47e8-7799-56c69aa3407d::b3de6324-4cf9-4197-b29d-edb59e8c92b7"
  },
  "thread_id": 47062168180480,
  "fiber_id": 47062182554640,
  "process_id": 4237,
  "file": "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/sinatra/vcap.rb",
  "lineno": 51,
  "method": "block in registered"
}
```

**Comment by will-gant** [comment]
A final update on this. We're now looking into whether our problems originate with the fact that we're using Pivotal Cloud Foundry, rather than `cf-deployment`. As such, throughout these issues we've been using [these release versions](https://docs.pivotal.io/pivotalcf/2-0/pcf-release-notes/runtime-rn.html#2.0.12). i.e. v1.44.31 of capi, and v1.32.1 of diego.

Does that sound like it might be behind our problem?

Thanks

**Comment by Infra-Red** [comment]
@bruxelles86 That shouldn't be a problem. We are using the same releases in Log Search PCF tile and I haven't seen such errors when working with PCF environment. Have you tried turning on Debug logging for Cloud Controller and UAA? Maybe then we can find some useful information.

**Comment by axelaris** [comment]
Closed because of no feedback from reporter for a long period of time
