### ISSUE TITLE
Action Failed get_task: Task result: 1 of 1 post-start scripts failed. Failed Jobs: elasticsearch.

### ISSUE THREAD

**Issue by StBurcher** [cloudfoundry-community/logsearch-boshrelease#52]
Hi,

I cannot deploy logsearch 204.0.0+dev.0 on CF-250. During the deployment, bosh aborts with the following error.

```
Deprecation: Ignoring cloud config. Manifest contains 'networks' section.

  Started preparing deployment > Preparing deployment. Done (00:00:01)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started updating instance cluster_monitor > cluster_monitor/35cc71dd-5a24-42de-ae19-4979a4f3a926 (0) (canary). Failed: Action Failed get_task: Task 96786c5e-04e3-4eb6-79a3-762b7e54b1eb result: 1 of 1 post-start scripts failed. Failed Jobs: elasticsearch. (00:01:26)

Error 450001: Action Failed get_task: Task 96786c5e-04e3-4eb6-79a3-762b7e54b1eb result: 1 of 1 post-start scripts failed. Failed Jobs: elasticsearch.
```

Using Bosh SSH into the cluster_monitor. I can found the following line in the elasticsearch.stdout.log

```
[WARN ][bootstrap                ] unable to load JNA native support library, native methods will be disabled.
java.lang.UnsatisfiedLinkError: /tmp/jna-3613596/jna2344870598325608331.tmp: /tmp/jna-3613596/jna2344870598325608331.tmp: failed to map segment from shared object: Operation not permitted
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:761)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:736)
        at com.sun.jna.Native.<clinit>(Native.java:131)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.elasticsearch.bootstrap.Natives.<clinit>(Natives.java:45)
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:89)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:144)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

All other logs in elastichsearch are empty.

Any Ideas?

**Comment by Infra-Red** [comment]
@StBurcher I suggest you to use stable Logsearch v204.0.0 release. Current repo HEAD is under development.

**Comment by StBurcher** [comment]
@Infra-Red thank you. So far so good.
But now. The next instance has problems

`Started updating instance maintenance > maintenance/b0f3cdc2-ed72-4d59-ae5b-e1adbc445cf0 (0) (canary). Failed: 'maintenance/0 (b0f3cdc2-ed72-4d59-ae5b-e1adbc445cf0)' is not running after update. Review logs for failed jobs: elasticsearch_config (00:10:30)`

`

The log shows:

```
Error 400007: 'maintenance/0 (b0f3cdc2-ed72-4d59-ae5b-e1adbc445cf0)' is not running after update. Review logs for failed jobs: elasticsearch_config

/var/vcap/sys/log/elasticsearch_config# cat job.control.log
{"error":{"root_cause":[{"type":"parse_exception","reason":"Failed to derive xcontent"}],"type":"parse_exception","reason":"Failed to derive xcontent"},"status":400}+ exit 400
```

**Comment by StBurcher** [comment]
Okay that worked
