### ISSUE TITLE
elasticsearch_data will not start on v206.x

### ISSUE THREAD

**Issue by janaurka** [cloudfoundry-community/logsearch-boshrelease#63]
Hey

When updating to `v206.x` we see the following error on the `elasticsearch_data` nodes:

```
2017-04-19 09:12:44,311 main ERROR Could not register mbeans java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:585)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1848)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:322)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
        at org.apache.logging.log4j.core.jmx.Server.register(Server.java:389)
        at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:167)
        at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:140)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:541)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:258)
        at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:117)
        at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:84)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
        at org.elasticsearch.cli.Command.main(Command.java:88)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84)

```

The `ctl` file looks like this: https://gist.github.com/janaurka/598c3e6a833e8d4d03803534ed45ade7

The `manifest` like this:

```
- azs:
  - az1
  - az2
  - az3
  instances: 3
  jobs:
  - name: elasticsearch
    properties:
      elasticsearch:
        cluster_name: logsearch
        drain: false
        health:
          disable_post_start: true
        heap_size: 30G
        master_hosts:
        - <ip>
        - <ip>
        - <ip>
        node:
          allow_data: true
          allow_master: false
    release: logsearch
  - name: syslog_forwarder
    properties:
      syslog_forwarder:
        config:
        - file: "/var/vcap/sys/log/elasticsearch/elasticsearch.stdout.log"
          service: elasticsearch
        - file: "/var/vcap/sys/log/elasticsearch/elasticsearch.stderr.log"
          service: elasticsearch
    release: logsearch
  name: elasticsearch_data
  networks:
  - name: dynamic
  persistent_disk_type: 400gb
  stemcell: trusty
  update:
    max_in_flight: 3
  vm_type: 8cpu_32gbram_20gbdis
```

This does not happen on `v205.x`. 

We run on `bosh Version    261.4.0 (00000000)` and use the latest `vsphere_cpi`.

**Comment by janaurka** [comment]
I was able to debug this. 

The problem is that `/var/vcap/packages/elasticsearch` belongs to `root` and the user `vcap` cannot access some data.

I’ll create a PR with a fix in some minutes.

**Comment by Infra-Red** [comment]
Hi @janaurka, I guess that Elasticsearch trying to use `jvm.options` config which stored in Elastcsearch package dir, we can add `jvm.options` file to job config and set `ES_JVM_OPTIONS` to the path of the file.

**Comment by janaurka** [comment]
@Infra-Red: yeah, I guess you are correct.

I’ve worked-around with a `chown -R vcap:vcap /var/vcap/packages/elasticsearch/` but a `ps` then looks like:

```
elasticsearch_data/aef1a704-d826-4273-9c8a-4e0df8b29a17:~# ps aux |grep java
vcap     22151 10.6 98.3 38370568 32415064 ?   S<Ll 11:48   6:26 /var/vcap/packages/java8/bin/java -Xms2g -Xmx2g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -server -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -Djdk.io.permissionsUseCanonicalPath=true -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Dlog4j.skipJansi=true -XX:+HeapDumpOnOutOfMemoryError -Xms30G -Xmx30G -Djava.io.tmpdir=/var/vcap/sys/tmp/elasticsearch -Des.path.home=/var/vcap/packages/elasticsearch -cp /var/vcap/packages/elasticsearch/lib/elasticsearch-5.3.0.jar:/var/vcap/packages/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch -p /var/vcap/sys/run/elasticsearch/elasticsearch.pid
```

check the `-Xms` and the `-Xmx` which shows up twice. Once the setting from the `jvm.options` in the `packages` dir and once the setting I’ve provided.

**Comment by janaurka** [comment]
@Infra-Red: My experience with those `jvm.options` is relatively small. Is this something you can do easily? I would have to look up every setting since I am really no JVM specialst...

**Comment by Infra-Red** [comment]
@jabrena Yes, i can handle it. Thanks for submitting the issue!

**Comment by Infra-Red** [comment]
Fixed https://github.com/cloudfoundry-community/logsearch-boshrelease/commit/4508d9acab0dfe3a43af57cfa4fe3d885f70e47b.

**Comment by janaurka** [comment]
fyi: I’ve applied the patch and looks good. great work, thx!
